In [4]:
import numpy as np
from numpy import array
from numpy.linalg import norm
from scipy.linalg import expm
from numpy import dot
import plotly.express as px
import pandas as pd
from cogent3.maths.matrix_exponential_integration import expected_number_subs
import math
from clock_project.maths.evolutionary_rate import calculate_stationary_distribution, calculate_stationary_rate, matrix_calibration

In [2]:
#testing rate matrices and nucleotide distributions
Q1 = array([[-1.4, 0.1, 0.4, 0.9], 
           [4.0, -6.9, 0.9, 2.0], 
           [6.3, 2.0, -11.3, 3.0], 
           [0.7,0.1, 0.2, -1]])

Q2 = np.array([[-0.0935, 0.0148, 0.0558, 0.0229], 
           [0.0469, -0.0676, 0.0108, 0.0099], 
           [0.00, 0.0058, -0.0319, 0.0261], 
           [0.00,0.0132, 0.0370, -0.0502]])

Q3= np.array([
    [-4.5,  2.0,  1.0,  1.5],
    [ 2.0, -3.5,  0.5,  1.0],
    [ 1.0,  0.5, -2.5,  1.0],
    [ 0.0,  1.0,  2.0, -3.0]
])

Q4 = np.array([[-1.707,  0.537,  0.306,  0.864],
       [ 0.249, -0.889 ,  0.116,  0.525 ],
       [ 0.038,  0.182, -0.555,  0.335],
       [ 0.203,  0.580,  0.234, -1.017]])

Q5 = np.array([[-1.87,  0.59,  0.33,  0.95],
       [ 0.27, -0.97,  0.13,  0.57],
       [ 0.04,  0.20, -0.60,  0.36],
       [ 0.23,  0.62,  0.25, -1.10]])

Q6 = np.array([[-4.56,  1.59,  2.33,  0.64],
       [ 0.55, -1.98,  1.13,  0.3],
       [ 0.73,  1.43, -4.52,  2.36],
       [ 0.15,  0.37,  1.8, -2.32]])

Q7 = np.array([[-0.7,  0.2,  0.1,  0.4],
       [ 0.0286, -0.7286,  0.6,  0.1],
       [ 0.0143,  0.6, -0.9143,  0.3],
       [ 0.08,  0.14,  0.42, -0.64]])
i = np.array([0.25, 0.25, 0.25, 0.25])

test_nst_array1 = np.array([0.3, 0.4, 0.2, 0.1])
test_nst_array2 = np.array([0.7, 0.1, 0.1, 0.1])
test_nst_array3 = np.array([0.05, 0.35, 0.35, 0.25])

Q_list = [Q1, Q3, Q4, Q5, Q6, Q7]


In [8]:
calculate_stationary_distribution(Q6)

array([0.09094403, 0.32120826, 0.25838462, 0.32946309])

In [3]:
np.linalg.norm(Q2.tolist())

for Q in Q_list:
    norm = np.linalg.norm(Q.tolist())
    print(norm)

15.91477301126221
8.215838362577491
2.6655627923573664
2.9074043406447614
8.49173716032238
1.870781895358195


In [4]:
#eigenvalue evaluation
for Q in Q_list:
    eigen = np.linalg.eig(Q)[0]
    print(eigen)

[-1.18618678e+01 -6.78553199e+00 -7.38493586e-16 -1.95260019e+00]
[ 8.88178420e-16 -5.94755326e+00 -3.35379921e+00 -4.19864753e+00]
[ 3.22540232e-04 -7.37451720e-01 -1.89802999e+00 -1.53284083e+00]
[ 4.44089210e-16 -2.08758338e+00 -7.99932583e-01 -1.65248404e+00]
[-6.36955280e+00 -4.66172958e+00 -1.30708102e-15 -2.34871762e+00]
[ 2.22044605e-16 -6.46125814e-01 -8.54566217e-01 -1.48220797e+00]


In [5]:
np.linalg.eig(Q6)[0]

array([-6.36955280e+00, -4.66172958e+00, -1.30708102e-15, -2.34871762e+00])

In [6]:
dot(Q1, Q1)

array([[ 5.5100e+00,  6.0000e-02, -4.8100e+00, -7.6000e-01],
       [-2.6130e+01,  5.0010e+01, -1.4380e+01, -9.5000e+00],
       [-6.9910e+01, -3.5470e+01,  1.3261e+02, -2.7230e+01],
       [-2.0000e-02, -3.2000e-01, -2.0900e+00,  2.4300e+00]])

In [8]:
#stationary process ENS accumulation function
def generate_ENS(Q1, Q2, t_range, t1):
    """
    Generates the ENS over a range of time points using two different Q matrices before and after a specified time point t1.
    
    Parameters:
    - pi: A numpy array of shape (1, 4) representing the vector pi.
    - Q1, Q2: Two numpy arrays of shape (4, 4) representing the original and new rate matrices.
    - t_range: numpy.linspace defining the start and end of the time range.
    - t1: The time point at which to switch from using Q1 to Q2.
    
    Returns:
    - A list of ENS values for each time point in the range.
    """
    pi = calculate_stationary_distribution(Q1)

    ens_values = []
    ens_accumulated = 0  # To keep track of the accumulated ENS value
    
    for t in t_range:
        if t <= t1:
            ens = -np.sum(pi * np.diag(Q1)) * t + ens_accumulated
            ens_values.append(ens)
        else:
            ens_2 = -np.sum(pi * np.diag(Q2)) * (t-t1) + ens # Update the accumulated ENS at t1 to continue from this point using Q2
            ens_values.append(ens_2)
    
    return ens_values

In [29]:
# Ploting the ENS over time with rate matrix switch in the middle
t_range =  np.linspace(0, 10, 999)
t1 = 5  #The time point that change the rate matrix

# Generate ENS values
ens_values = generate_ENS(Q5, Q6, t_range, t1)

# Create the plot
fig_ = px.line(x=t_range, y=ens_values, labels={'x': 'Time (t)', 'y': 'ENS'}, title='ENS Over Time with Rate Matrix Switch at t=5')

# Show the plot
fig_.show()

In [30]:
# Ploting the evolutionary rate mu over time with rate matrix switch in the middle

mu_value = []

# Generate mu values
for t in t_range:
    if t<= t1:
        mu = calculate_stationary_rate(Q5)
        mu_value.append(mu)
    else:
        mu = calculate_stationary_rate(Q6)
        mu_value.append(mu)
    
# Create the plot
fig = px.line(x=t_range, y=mu_value, labels={'x': 'Time (t)', 'y': 'Evolutionary rate'}, title=None)


fig.update_layout(
    xaxis=dict(
        title_font=dict(size=25),
        tickfont=dict(size=20),
    ),
    yaxis=dict(
        title_font=dict(size=25),
        tickfont=dict(size=20),
    ),
    template='plotly_white'
)

fig.write_image("evolutionary_rate_change_stationary.pdf")

# Show the plot
fig.show()

In [11]:
#non-stationary process 
#evolution rate at each time point in non-stationary process

def calculate_non_statioanry_mu(Q, pi_0, t):
    """
    Calculate the value of mu prime (μ(t)) for a given substitution rate matrix Q,
    initial nucleotide frequency pi_0, and time t.

    Parameters:
    Q (numpy.ndarray): The substitution rate matrix.
    pi_0 (numpy.ndarray): The initial nucleotide frequency distribution.
    t (float): The time at which to calculate μ(t).

    Returns:
    float: The calculated value of μ(t).
    """
    # Calculate f(t) = pi_0 * exp(Qt)
    f_t = dot(pi_0, expm(Q * t))
    
    # Calculate mu'(t) as the sum of the element-wise product of f(t) and the diagonal of Q
    mu = - dot(f_t,np.diagonal(Q))
    
    return mu

In [12]:
#derivative of evolution rate
def calculate_non_stationary_mu_prime(Q, pi_0, t):
    """
    Correctly calculate the value of mu prime (μ'(t)) based on the provided formula:
    μ'(t) = - pi_0 * Q * exp(Qt) * diag(Q)

    Parameters:
    Q (numpy.ndarray): The substitution rate matrix.
    pi_0 (numpy.ndarray): The initial nucleotide frequency distribution.
    t (float): The time at which to calculate μ'(t).

    Returns:
    numpy.ndarray: The calculated value of μ'(t) as a vector.
    """
    
    # Calculate μ'(t) using the provided formula
    mu_prime_t = -pi_0.dot(Q).dot(expm(Q * t)).dot(np.diagonal(Q))
    
    return mu_prime_t


In [13]:
#Calculate the range of evolution rate and its derivation given a time intervel and initial nucleotide frequency
def mu_mu_prime_range(Q, pi_0, t_range):
    """
    Calculate the range of evolution rate and its derivation 
    given a time intervel and initial nucleotide frequency

    Parameters:
    Q (numpy.ndarray): The substitution rate matrix.
    pi_0 (numpy.ndarray): The initial nucleotide frequency distribution.
    t_range (numpy.linspace): The time interval for calculating the evolutionary rate and its derivative

    Returns:
    lists: The calculated value of μ(t) and μ'(t) over the time inteval as lists.
    """
    mu_range = []
    mu_prime_range = []
    for t in t_range:
        mu = calculate_non_statioanry_mu(Q, pi_0, t)
        mu_prime = calculate_non_stationary_mu_prime(Q, pi_0, t)
        mu_range.append(mu)
        mu_prime_range.append(mu_prime)
    
    return mu_range, mu_prime_range

In [14]:
#test the evolution rate using the testing Q and pi
t_range_large =  np.linspace(0, 100, 1000)
t_range_small = np.linspace(0, 0.5, 100)
mu_range1, mu_prime_range1 = mu_mu_prime_range(Q2, test_nst_array3, t_range_large)

In [15]:
df1 = pd.DataFrame({'Time': t_range_large, 'Evolutionary rate': mu_range1})
fig1 = px.line(df1, x='Time', y='Evolutionary rate')
# Update axis label font size
fig1.update_layout(
    xaxis=dict(
        title_font=dict(size=25),
        tickfont=dict(size=20),
    ),
    yaxis=dict(
        title_font=dict(size=25),
        tickfont=dict(size=20),
    )
)

# fig1.write_image("evolutionary_rate_change_non-stationary.pdf")


fig1.show()




In [16]:
df2 = pd.DataFrame({'Time': t_range_large, 'Mu_prime': mu_prime_range1})
fig2 = px.line(df2, x='Time', y='Mu_prime')
fig2.update_layout(
    xaxis=dict(
        title_font=dict(size=25),
        tickfont=dict(size=20),
    ),
    yaxis=dict(
        title_font=dict(size=25),
        tickfont=dict(size=20),
    )
)

fig2.show()

In [17]:
#the change of evolution rate when change the evolution into a non-stationary process
def generatenon_non_stationary_mu(Q1, Q2, t_range, t1):
    """
    Generates the ENS over a range of time points using two different Q matrices before and after a specified time point t1.
    
    Parameters:
    - pi: A numpy array of shape (1, 4) representing the vector pi.
    - Q1, Q2: Two numpy arrays of shape (4, 4) representing the original and new rate matrices, with same stationary distribution.
    - t_range: numpy.linspace defining the start and end of the time range.
    - t1: The time point at which to switch from using Q1 to Q2.
    
    Returns:
    - A list of evolutionary rate values for each time point in the range.
    """
    mu_values = []
    pi = calculate_stationary_distribution(Q1)
    
    for t in t_range:
        if t <= t1:
            mu = -np.sum(pi * np.diag(Q1))
            mu_values.append(mu)
        else:
            f_t = dot(pi, expm(Q2 * (t-t1)))
            mu_2 = - dot(f_t,np.diagonal(Q2)) # Update the evolutionary rate at t1 to continue from this point using Q2
            mu_values.append(mu_2)

            
    
    return mu_values

In [27]:
# Ploting the mu over time with rate matrix switch in the middle
t_range =  np.linspace(0, 10, 999)
t1 = 3  #The time point that change the rate matrix

# Generate mu values
non_stationary_mu_values = generatenon_non_stationary_mu(Q1, Q4, t_range, t1)

# Create the plot
fig3 = px.line(x=t_range, y=non_stationary_mu_values, labels={'x': 'Time (t)', 'y': 'Evolutionary Rate'}, title=None)

fig3.update_layout(
    xaxis=dict(
        title_font=dict(size=25),
        tickfont=dict(size=20),
    ),
    yaxis=dict(
        title_font=dict(size=25),
        tickfont=dict(size=20),
    ),
    template='plotly_white'
)

# Show the plot
fig3.write_image("evolutionary_rate_change_non_stationary.pdf")
fig3.show()

In [19]:
#calculate the accumulation of ENS where the rate matrix change in the middle

def generate_non_stationary_ENS(Q1, Q2, t_range, t1):
    """
    Generates the ENS over a range of time points using two different Q matrices before and after a specified time point t1.
    
    Parameters:
    - pi: A numpy array of shape (1, 4) representing the vector pi.
    - Q1, Q2: Two numpy arrays of shape (4, 4) representing the original and new rate matrices, with different stationary distribution.
    - t_range: numpy.linspace defining the start and end of the time range.
    - t1: The time point at which to switch from using Q1 to Q2.
    
    Returns:
    - A list of ENS values for each time point in the range.
    """

    pi = calculate_stationary_distribution(Q1)
    ens_values = []
    ens_accumulated = 0  # To keep track of the accumulated ENS value
    
    for t in t_range:
        if t <= t1:
            ens = -np.sum(pi * np.diag(Q1)) * t + ens_accumulated
            ens_values.append(ens)
        else:
            ens_2 = expected_number_subs(pi, Q2, t-t1) + ens # Update the accumulated ENS at t1 to continue from this point using Q2
            ens_values.append(ens_2)
    
    return ens_values

In [20]:
non_stationary_ENS_value = generate_non_stationary_ENS(Q6, Q1, t_range, t1)
# Create the plot
fig4 = px.line(x=t_range, y=non_stationary_ENS_value, labels={'x': 'Time (t)', 'y': 'ENS'}, title='ENS Over Time with Rate Matrix Switch at t=5')

fig4.update_layout(
    xaxis=dict(
        title_font=dict(size=25),
        tickfont=dict(size=20),
    ),
    yaxis=dict(
        title_font=dict(size=25),
        tickfont=dict(size=20),
    )
)

# Show the plot
fig4.show()

In [21]:
#calculate the nabla statistic 

def calculate_nabla_statistic(pi_0, Q, t_range):
    """
    Generates the nabla value over a range of time t based on the initial nucleotide freqeuncy distribution pi and subatituiton rate .
    
    Parameters:
    - pi: A numpy array of shape (1, 4)represnting the initial nucleotide freqeuncy distirbution
    - Q1, Q2: A numpy arrays of shape (4, 4) representing the rate matrices.
    - t_range: numpy.linspace defining the start and end of the time range.
    
    Returns:
    - A list of nabla values for each time point in the range.
    """

    nabla_values = []
    for t in t_range:
        pi_deriv = dot(pi_0, dot(Q, expm(Q * t)))
        conv = norm(pi_deriv)
        nabla_values.append(conv)


    return nabla_values
    

In [22]:
# Ploting the mu over time with rate matrix switch in the middle
t_range =  np.linspace(0, 10, 999)

# Generate mu values
nabla_values = calculate_nabla_statistic(test_nst_array2, Q6, t_range)

TypeError: 'numpy.float64' object is not callable

In [ ]:
fig5 = px.line(x=t_range, y=nabla_values, labels={'x': 'Time (t)', 'y': 'Nabla'}, title='Nabla Over Time')

fig5.update_layout(
    xaxis=dict(
        title_font=dict(size=25),
        tickfont=dict(size=20),
    ),
    yaxis=dict(
        title_font=dict(size=25),
        tickfont=dict(size=20),
    )
)

# Show the plot
fig5.show()

In [ ]:
t = 1
expm(Q3 * (t))

array([[0.1797868 , 0.23250177, 0.31641591, 0.27129552],
       [0.18254742, 0.24253598, 0.30604158, 0.26887503],
       [0.17134336, 0.21410492, 0.34885823, 0.26569349],
       [0.16332084, 0.21493464, 0.34034611, 0.28139841]])