In [3599]:
import numpy as np
from clock_project.simulation.magnitude_quantification import calculate_ENS, calculate_non_stationarity
from clock_project.simulation.waiting_time_simulator_original import generate_rate_matrix
from clock_project.maths.evolutionary_rate import calculate_stationary_distribution
import numpy as np
from scipy.stats import entropy
from cogent3.maths.measure import jsd

In [3178]:
pi_balance = [0.25, 0.25, 0.25, 0.25]

In [3198]:
num_generate = 50000
Q_norm_list = []

In [3470]:
for i in range(num_generate):
    Q1 = generate_rate_matrix()
    norm = np.linalg.norm(Q1)
    Q_norm_list.append(norm)

In [3471]:
import plotly.express as px

fig = px.histogram(Q_norm_list)
fig.show()

In [3472]:
range_norm = [min(Q_norm_list), max(Q_norm_list)]
range_norm

[1.3824278897184337, 5.825238869051143]

In [3473]:
# seed = 1
# Q1 = generate_rate_matrix()
# p0 = calculate_stationary_distribution(np.array(Q1))


In [3475]:
import json
with open ("/Users/gulugulu/repos/PuningAnalysis/data/dataset1_16s-10_initial_alignments/matrix_motif.json", 'r') as infile:
    matrix_motif = json.load(infile)
matrix = matrix_motif['0']['matrix']['200580']
motif = matrix_motif['0']['motif_prob']
-np.dot(motif, np.diag(matrix))
calculate_non_stationarity(np.array(motif), np.array(matrix), 1)

0.22931117235847018

In [4725]:
t = 0.2
Q1 = generate_rate_matrix()
p0 = calculate_stationary_distribution(np.array(Q1))
ens1 = calculate_ENS(p0, Q1, t)
nabla1 = calculate_non_stationarity(p0, np.array(Q1), t)
nabla1, ens1, p0

(4.0209677794196317e-16,
 0.1753308920895844,
 array([0.2448779 , 0.49406287, 0.16111337, 0.09994586]))

In [4726]:
jsd(p0, pi_balance)

0.06039693005497848

In [4727]:
t = 0.2
ens_differnce_list = []
nabla_list = []
for i in range(2000):
    Q2 = generate_rate_matrix()
    ens2 = calculate_ENS(motif, np.array(Q2), t)
    nabla2 = calculate_non_stationarity(motif, np.array(Q2), t)
    ens_difference = np.sqrt((ens1-ens2)**2)
    ens_differnce_list.append(ens_difference)
    nabla_list.append(abs(nabla2+nabla1))

In [4728]:
np.corrcoef(ens_differnce_list, nabla_list)[0][1]

0.3948535619179222

In [4729]:
fix = px.scatter(x = nabla_list, y = ens_differnce_list)
fix.show()

In [4730]:
interesting_Q_list = [[[-0.43467944426062116,
  0.17224055426099708,
  0.16310857726796912,
  0.09933031273165498],
 [0.8744884057309638,
  -2.508370983023648,
  0.658828378197184,
  0.9750541990955003],
 [0.37647486131169944,
  0.5579123848326735,
  -1.236392734665995,
  0.3020054885216221],
 [0.55032999104189,
  0.5277845913495285,
  0.2731367973092342,
  -1.3512513797006527]], 
  
  [[-1.0324510784624759,
  0.4705794305451246,
  0.1630045451999826,
  0.39886710271736864],
 [0.9008293238961476,
  -1.5034040948261855,
  0.38980500390391093,
  0.212769767026127],
 [0.2766980368416016,
  0.9871872426447907,
  -1.4601095568968394,
  0.19622427741044704],
 [0.9317938668773915,
  0.6880911187655664,
  0.18876499162501448,
  -1.8086499772679723]], 
  
  [[-0.0836110718980669,
  0.02928686007361185,
  0.04357023499776807,
  0.010753976826686976],
 [0.42617291612837976,
  -1.407700943023633,
  0.3404865281419312,
  0.641041498753322],
 [0.4709650739106473,
  0.7359344407599814,
  -1.270471438911452,
  0.06357192424082321],
 [0.5738417345245591,
  0.9707017736872785,
  0.8269744361549397,
  -2.371517944366777]], 
  
  [[-1.3874938561237078,
  0.35200366828334734,
  0.5322473376832975,
  0.5032428501570629],
 [0.12568809061238725,
  -0.22806904582294607,
  0.06943901192785681,
  0.032941943282702],
 [0.48709368515201384,
  0.33827174062165477,
  -0.854879002815376,
  0.029513577041707324],
 [0.8536063381533379,
  0.7822134852029212,
  0.6494128004287897,
  -2.2852326237850487]], 
  
  [[-2.136629625047819,
  0.9700439277212034,
  0.9157328283601847,
  0.2508528689664307],
 [0.10269693977219942,
  -0.2924420974628559,
  0.16441136011823673,
  0.02533379757241972],
 [0.9094847232073033,
  0.28484073919589353,
  -1.5520634331233163,
  0.3577379707201194],
 [0.3652230897725877,
  0.661147712658651,
  0.011537216013910346,
  -1.0379080184451492]], 
  
  [[-2.136629625047819,
  0.9700439277212034,
  0.9157328283601847,
  0.2508528689664307],
 [0.10269693977219942,
  -0.2924420974628559,
  0.16441136011823673,
  0.02533379757241972],
 [0.9094847232073033,
  0.28484073919589353,
  -1.5520634331233163,
  0.3577379707201194],
 [0.3652230897725877,
  0.661147712658651,
  0.011537216013910346,
  -1.0379080184451492]], 

  [[-0.7070916577603472,
  0.18599021415027228,
  0.45684711552471124,
  0.0642543280853637],
 [0.09534346457249147,
  -0.7747103246960625,
  0.4658892931984096,
  0.21347756692516137],
 [0.07026922858025701,
  0.1998051126643552,
  -0.34182192709856724,
  0.071747585853955],
 [0.8926981689288437,
  0.03439508051023827,
  0.3950013493306266,
  -1.3220945987697086]]]

In [4731]:
Q_array_list = [np.array(Q) for Q in interesting_Q_list]
# Stack the matrices and compute the element-wise mean
average_matrix = np.mean(np.stack(Q_array_list), axis=0)

average_matrix

array([[-1.13122662,  0.45002694,  0.45574907,  0.22545062],
       [ 0.37541658, -1.00101994,  0.32189585,  0.30370751],
       [ 0.50006719,  0.4841132 , -1.1811145 ,  0.19693411],
       [ 0.6475309 ,  0.61792592,  0.33662354, -1.60208037]])

In [4732]:
for Q in interesting_Q_list:
    print(np.linalg.eigvals(Q))

[-2.97808390e+00 -6.66133815e-16 -9.83677362e-01 -1.56893328e+00]
[ 2.22044605e-16+0.j         -1.45401422e+00+0.j
 -2.17530024e+00+0.12417911j -2.17530024e+00-0.12417911j]
[ 0.         -0.55124187 -2.71202069 -1.87003884]
[-2.60378354e+00 -1.54404705e+00  1.96714807e-16 -6.07843942e-01]
[-2.79844207e+00  3.38271078e-17 -1.00160154e+00 -1.21899956e+00]
[-2.79844207e+00  3.38271078e-17 -1.00160154e+00 -1.21899956e+00]
[ 2.22044605e-16 -1.32385645e+00 -7.99857907e-01 -1.02200415e+00]


In [4733]:
pi_list = []
for Q in interesting_Q_list:
    pi = calculate_stationary_distribution(np.array(Q))
    pi_list.append(pi)
    print(pi)
    print(jsd(pi, pi_balance))

[0.5650861  0.10932365 0.16768575 0.1579045 ]
0.07895556387559877
[0.42193655 0.29168266 0.14345276 0.14292803]
0.03839909347149972
[0.84822741 0.066259   0.06209234 0.02342125]
0.2879598944096333
[0.14593838 0.63497631 0.17552728 0.04355803]
0.13503878237706513
[0.10428462 0.67437729 0.13361837 0.08771972]
0.13750338824532715
[0.10428462 0.67437729 0.13361837 0.08771972]
0.13750338824532715
[0.17055524 0.19073893 0.56875315 0.06995268]
0.0930590787854515


In [4734]:
jsd([0.25, 0.25, 0.25, 0.25], pi_balance)

0.0

In [4735]:
calculate_stationary_distribution(np.array(interesting_Q_list[-1]))

array([0.17055524, 0.19073893, 0.56875315, 0.06995268])

In [4755]:
sample_size = 10000
t = 0.1
num_generate = 2000
jsd_list = []
correlation_List = []
correlation_factor_list = []

for i in range(sample_size):
    Q1 = generate_rate_matrix()
    pi = calculate_stationary_distribution(np.array(Q1))
    # print(pi)
    jsd_pi = jsd(pi, pi_balance)
    ens1 = calculate_ENS(pi, Q1, t)
    nabla1 = calculate_non_stationarity(pi, np.array(Q1), t)
    jsd_list.append(jsd_pi)
    for i in range(num_generate):
        Q2 = generate_rate_matrix()
        ens2 = calculate_ENS(pi, np.array(Q2), t)
        nabla2 = calculate_non_stationarity(pi, np.array(Q2), t)
        ens_difference = np.sqrt((ens1-ens2)**2)
        ens_differnce_list.append(ens_difference)
        nabla_list.append(abs(nabla2+nabla1))
    correlation_factor = np.corrcoef(ens_differnce_list, nabla_list)[0][1]
    correlation_factor_list.append(correlation_factor)
        
        


KeyboardInterrupt: 

In [ ]:
entropy_correlation_fig = px.scatter(x = jsd_list, y = correlation_factor_list)
entropy_correlation_fig.show()

In [ ]:
correlation_fig = px.box(correlation_factor_list)
correlation_fig